#!/usr/bin/env bash
export GIT_DIR=$HOME/.tools/.repo
export GIT_WORK_TREE=$HOME

git config --local status.showUntrackedFiles no

if ! git checkout; then
  echo
  read -p "Checkout failed. Try again with --force? [y/n] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    exit 1
  fi
  git checkout --force || exit 1
fi
