#!/usr/bin/env bash
set -euo pipefail

function git_parent() {
  git show-branch 2>/dev/null \
    | sed "s/].*//" \
    | grep "\*" \
    | grep -v "$(git rev-parse --abbrev-ref HEAD)" \
    | head -n1 \
    | sed "s/^.*\[//"
}

git_parent
