#!/usr/bin/env bash
set -euo pipefail

function rc__init {
  local protocol=${1:-""}
  local git_url=""

  if [[ $protocol == "https" ]]; then
    git_url="https://github.com/andybarron/dotfiles.git"
  elif [[ $protocol == "ssh" || $protocol == "" ]]; then
    git_url="git@github.com:andybarron/dotfiles.git"
  else
    echo "Unknown git protocol: $protocol" >&2
    return 1
  fi

  git clone --bare "$git_url" "$HOME/.dotfiles/.gitbare"
  git --git-dir "$HOME/.dotfiles/.gitbare" --work-tree "$HOME" checkout \
    --force
  if [[ "$(ps -p $$ -ocommand=)" == *"zsh"* ]]; then
    exec zsh
  else
    zsh -i
  fi
}

rc__init "$@"
