#!/usr/bin/env bash
set -euo pipefail

function init_dotfiles {
  local protocol=${1:-""}
  local git_url=""

  if [[ $protocol == "https" ]]; then
    git_url="https://github.com/andybarron/dotfiles.git"
  elif [[ $protocol == "ssh" || $protocol == "" ]]; then
    git_url="git@github.com:andybarron/dotfiles.git"
  else
    echo "Unknown git protocol: $protocol" >&2
    return 1
  fi

  git clone --bare "$git_url" "$HOME/.dotfiles/.gitbare"
  git --git-dir "$HOME/.dotfiles/.gitbare" --work-tree "$HOME" checkout \
    --force

  # configure bare repo not to show untracked files
  git --git-dir "$HOME/.dotfiles/.gitbare" config --local status.showUntrackedFiles no

  exec zsh -i
}

init_dotfiles "$@"
