#!/bin/bash
set -euo pipefail

# script args are passed to stow.
# - dry run: -nv
# - delete symlinks: -D
# - dry run deletion: -Dnv

cd ~/.dotfiles/packages
# shellcheck disable=SC2035
stow -t ~ --no-folding "$@" *

# remove bogus symlinks in ~/.config
find ~/.config -type l ! -exec test -e {} \; -delete
