#!/bin/bash
set -euo pipefail

# script args are passed to stow.
# - dry run: -nv
# - delete symlinks: -D
# - dry run deletion: -Dnv

cd ~/.dotfiles/packages

# on apple silicon, homebrew installs to `/opt/homebrew/bin`. this directory
# is not in $PATH by default. `.zshenv` adds it to $PATH, but our `.zshenv`
# won't exist until after `stow` is run!
# workaround: if `brew` is not found, but `/opt/homebrew/bin` exists, run
# `brew shellenv` to add it to the PATH. this is only necessary during initial
# setup on apple silicon.
if [[ "${OSTYPE:-}" == darwin* ]] && ! command -v stow &>/dev/null; then
  # if brew command is not found but /opt/homebrew/bin exists, run brew shellenv
  if ! command -v brew &>/dev/null && [[ -d /opt/homebrew/bin ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  # if brew is still not found, error
  if ! command -v brew &>/dev/null; then
    echo "brew not found" 1>&2
    exit 1
  fi
fi

if ! command -v stow &>/dev/null; then
  echo "stow not found" 1>&2
  exit 1
fi

# load all directories in cwd into packages
packages=()
for package in */; do
  packages+=("$(basename "$package")")
done

stow -t ~ --no-folding "$@" "${packages[@]}"

# remove bogus symlinks in ~/.config
find ~/.config -type l ! -exec test -e {} \; -delete
