#!/usr/bin/env bash
set -euo pipefail

function init_dotfiles {
  local protocol=${1:-""}
  local git_url=""
  local git_dir="$HOME/.config/dotfiles/.gitbare"

  if [[ $protocol == "https" ]]; then
    git_url="https://github.com/andybarron/dotfiles.git"
  elif [[ $protocol == "ssh" || $protocol == "" ]]; then
    git_url="git@github.com:andybarron/dotfiles.git"
  else
    echo "Unknown git protocol: $protocol" >&2
    return 1
  fi

  git clone --bare "$git_url" "$git_dir"
  git --git-dir "$git_dir" --work-tree "$HOME" checkout --force
  git --git-dir "$git_dir" --work-tree "$HOME" submodule update --init --recursive

  # configure bare repo not to show untracked files
  git --git-dir "$git_dir" config --local status.showUntrackedFiles no

  # if zsh is not installed, exit
  if ! command -v zsh &>/dev/null; then
    echo "init successful, but zsh is not installed. exiting" >&2
    return
  fi

  # if default shell is not zsh, offer to change it
  if [[ "$SHELL" != "$(which zsh)" ]]; then
    read -p "Change default shell to zsh? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      chsh -s "$(which zsh)"
    fi
  fi

  read -p "start zsh? [Y/n] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
    exec zsh -i
  fi
}

init_dotfiles "$@"
