# https://alacritty.org/config-alacritty.html
import = ["~/.dotfiles/local/repos/alacritty-theme/themes/horizon-dark.toml"]

[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
padding = { x = 8, y = 0 }
dynamic_padding = true
